added confirmationDialog
apbetioli/estimate3d pull request #33
Opened 2024-02-18 20:53 UTC by AryanKuAg

![image](https://github.com/apbetioli/estimate3d/assets/61811630/c625abaa-edf8-4022-af41-f09390ca3721)

2024-02-19 10:52 UTC, apbetioli requested changes
@AryanKuAg Thank you for the PR. That's exactly what I had in mind, there are just a few adjustments to do. In addition to the other comments, make sure that you run the following:

- Check eslint rules: `npm run lint`
- Check typescript types: `npm run typecheck`
- Format code: `npm run format`

I was expecting that GH would run these checks automatically on the PR, but I missed some configuration. I'm going to check it.

If you use vscode, add the ESLint plugin to help with those checks while developing.
I also recommend installing Prettier and Tailwind CSS Intellisense.

2024-02-19 10:52 UTC, apbetioli commented on src/components/ConfirmationDialog.tsx
> +                    className="text-2xl font-medium leading-6 text-[#9e9fa2]"
On `styles.css`, we already define the size of the `h3` element as `text-lg`. 
There's no need to define colors, it'll use the ones in the 'theme' for consistency.

```suggestion
```

2024-02-19 10:52 UTC, apbetioli commented on src/components/ConfirmationDialog.tsx
> +                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-[#161f29] p-6 text-left align-middle shadow-xl transition-all border border-[#dc2625]">
Let's use the tailwind color schemes instead of specific color codes and with preference for those already in use in the app for visual consistency. 
The red border: suggested the same color as used in the Settings page.
Use `rounded-lg` for consistency with the rest of the app.
The background color should match the 'theme' (dark/light). Suggesting the same colors as used in the Section component.
Please change the other places and buttons in this component to follow the same idea.

```suggestion
                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-lg bg-white dark:bg-gray-900 p-6 text-left align-middle shadow-xl transition-all border border-red-600">
```

2024-02-19 10:52 UTC, apbetioli commented on src/components/ConfirmationDialog.tsx
> +export default function ConfirmationDialog({isOpen, setIsOpen, name, deleteFn}: any) {
We should avoid using `any`, otherwise, there's no point in using Typescript. Please check the component `EmptyResult` as an example of how to define the component type.

2024-02-19 10:52 UTC, apbetioli commented on src/components/ConfirmationDialog.tsx
> +  }
`openModal` is never used. You could remove it.

2024-02-19 10:52 UTC, apbetioli commented on src/pages/Filaments.tsx
> +  const [deletingFilament, setDeletingFilament] = useState<any>();
Use the correct type here:

```suggestion
  const [deletingFilament, setDeletingFilament] = useState<Filament>();
```

2024-02-19 10:52 UTC, apbetioli commented on src/pages/Printers.tsx
> +  const [deletingPrinter, setDeletingPrinter] = useState<any>();
Same here
```suggestion
  const [deletingPrinter, setDeletingPrinter] = useState<Printer>();
```

2024-02-19 11:13 UTC, apbetioli commented
Don't forget to check the 'light' mode:

![image](https://github.com/apbetioli/estimate3d/assets/2829329/01a5a0cb-3a0d-46b6-a6a3-e0261915012b)

2024-02-19 19:30 UTC, apbetioli commented
I just remembered, let's add the confirmation to deleting all data too. 😉

2024-02-20 05:12 UTC, AryanKuAg commented on src/pages/Prints.tsx
> +  const [deletingPrint, setDeletingPrint] = useState<any>();
Done 🚀

2024-02-20 05:12 UTC, AryanKuAg commented on src/pages/Printers.tsx
> +  const [deletingPrinter, setDeletingPrinter] = useState<any>();
Done 🚀

2024-02-20 05:12 UTC, AryanKuAg commented on src/pages/Filaments.tsx
> +  const [deletingFilament, setDeletingFilament] = useState<any>();
Done 🚀

2024-02-20 05:13 UTC, AryanKuAg commented on src/components/ConfirmationDialog.tsx
> +  }
Done 🚀

2024-02-20 05:14 UTC, AryanKuAg commented on src/components/ConfirmationDialog.tsx
> +export default function ConfirmationDialog({isOpen, setIsOpen, name, deleteFn}: any) {
Done 🚀

2024-02-20 05:45 UTC, AryanKuAg commented on src/components/ConfirmationDialog.tsx
> +                    className="text-2xl font-medium leading-6 text-[#9e9fa2]"
Done 🚀

2024-02-20 05:55 UTC, AryanKuAg commented on src/components/ConfirmationDialog.tsx
> +                <Dialog.Panel className="w-full max-w-md transform overflow-hidden rounded-2xl bg-[#161f29] p-6 text-left align-middle shadow-xl transition-all border border-[#dc2625]">
Done 🚀

2024-02-20 06:25 UTC, AryanKuAg commented
Hi @apbetioli 🙂👋🏻, I'have fixed all the changes suggested by you. I wanna say really thank to you to provide such a detailed analysis on my code for improvements. I didn't worked with typescript before but learned it to contribute. I'll also show this level of dedication in your future projects. I've one request to u that can we connect sometime on discord or linkedin or anywhere u prefer cause I need some guidance from you, can u please be my mentor and guide me to boost my creativity in programming and business? I saw your profile, ur dedication for last 15 years in programming tells a lot. I'll love to contribute to your future projects (free/paid) if u persistently guide me like that. I really appreciate u for this. Thank u🙏.

2024-02-20 06:26 UTC, AryanKuAg commented
Also, please suggest me if there any issues with the current commits😼

2024-02-20 17:27 UTC, apbetioli requested changes
@AryanKuAg Thanks for the excellent work. It is looking great. I have 2 small additional suggestions, and it should be done. We can connect on LinkedIn and Discord. My username is `apbetioli` on all platforms. I'm happy to help with anything I can.

2024-02-20 17:27 UTC, apbetioli commented on src/pages/Filaments.tsx
> +                          setIsDialogOpen((pre) => !pre);
No problem with your code; it is correct. The suggestion here is an improvement in code readability. What is expected when clicking on the icon? Opening the modal. Unless something is wrong in the modal implementation, there won't be a case where we end up closing the modal when clicking the delete button. Simply passing `true` will communicate a better intention for the future dev reading it.

```suggestion
                          setIsDialogOpen(true);
```

2024-02-20 17:27 UTC, apbetioli commented on src/pages/Filaments.tsx
> +      />
A little bit of performance optimization. If there's no `deletingFilament`, the `ConfirmationDialog` component won't be rendered, and we gain a little bit of code improvement without the `if` statement and the optional chaining operator.


```suggestion
      {deletingFilament && (
        <ConfirmationDialog
          isOpen={isDialogOpen}
          setIsOpen={setIsDialogOpen}
          name={deletingFilament.name}
          deleteFn={() => remove(deletingFilament)}
        />
      )}
```

2024-02-20 17:59 UTC, AryanKuAg commented on src/pages/Filaments.tsx
> +                          setIsDialogOpen((pre) => !pre);
All done @apbetioli

2024-02-20 18:04 UTC, AryanKuAg commented
Hi @apbetioli ! Thanks again for these suggestions. I've fixed those 2 issues suggested by you. I tried to search ur name on linkedin but not able to find.
![image](https://github.com/apbetioli/estimate3d/assets/61811630/c66eda3e-b3ae-4f0d-8edb-ac7442503c67)
Also on discord, I'm not able to add u as a friend
![image](https://github.com/apbetioli/estimate3d/assets/61811630/3fb97fe3-8440-4c94-a14d-cab7393e2388)

2024-02-21 08:54 UTC, apbetioli commented
Thanks, It is looking good! Merging it. Good job! :rocket:

2024-02-21 08:54 UTC, merged